### ISSUE TITLE
[Feature] Toggle for the /server tab-complete feature.

### ISSUE THREAD

**Issue by ChevalGlass** [AnvilPowered/Catalyst#21]
The default behavior of velocity adds the /server \<servername\> command where the \<servername\> can be tab completed.

Request: Add a toggle to either
- Disable the /server (without an argument) command and re-enable the default behavior.
- Enable the /server \<servername\> tab-complete in addition to the /server (without an argument).

**Comment by STG-Allen** [comment]
I am thinking about adding the tab auto complete, and also adding the ability to disable each command or "module" in the config aswell

**Comment by STG-Allen** [comment]
Also, do note that if you are using the AdvancedServerInfo section of the config, you'll have to utilize the Catalyst server command in order for it to work properly

**Comment by ChevalGlass** [comment]
ok, great. Being able to toggle the modules would be a fantastic feature!

I just tried to enable the AdvancedServerInfo option, but it's still not clear to me what it does specifically. It doesn't let me connect to my server when it's enabled so I must not have configured it correctly. When that is enable does the /Catalyst command become available? It doesn't seem to be available by default.
Unless you mean adding the catalyst.command.server permission or something.

**Comment by STG-Allen** [comment]
The AdvancedServerInfo option needs more documentation, but it essentially allows you to have different A records that point to a specific server on the proxy. While doing that, It shows a custom MOTD. This is very useful especially in the Modded scene, I can provide more information about it if needed. 

As for the /catalyst command, It honestly isn't needed anymore as it was only there to reload the plugin (which you can do with /av reload catalyst). As for permission, there should be one there already. If not I can add it, but I plan to have it so if you disable the command via the config, it will not be loaded on the server.

**Comment by ChevalGlass** [comment]
ah, ok that makes more sense.

I'm hosting at home so if I happen to add another A record to miss-spellings or something that might be helpful.

I didn't have a problem adding the /server command permission. The tab-complete option is just essential to moving servers quickly. While the click menu in chat is great for newer players.

**Comment by STG-Allen** [comment]
Attached below is an example of how I personally have the A records setup. They are all pointed to the same port (typically 25577)

![image](https://user-images.githubusercontent.com/26695048/80922487-7dbfb200-8d4b-11ea-8850-2e695d892982.png)

**Comment by ChevalGlass** [comment]
oh I understand now.

That's a nice way to do multiple servers without requiring a proxy for each.
