### ISSUE TITLE
Can't use the %players% placeholder in the "playing" field

### ISSUE THREAD

**Issue by josua27176** [AnvilPowered/Catalyst#25]
**Describe the bug**
A clear description of the bug:
Inside the config where you set the game status for the discord bot you can not use the %players% placeholder to pull the player count if you wanted to show it in the game status section of the bot.
**To Reproduce**
Try to put %players% in the "playing" field
**Expected behavior**
%players% being replaced with the player count of the network.
**Screenshots**
https://gyazo.com/dd0367c3938cf52a29ba144fbde7cead

**Desktop (please complete the following information):**
 - Velocity Version: 1.1.0
 - Catalyst Version: 0.1.3
 - Additional Plugins installed on velocity: 

**Additional context**

**Comment by STG-Allen** [comment]
Added in commit 0897d4aee744df21e41d04130ccf83a17a881fff
