### ISSUE TITLE
(Bug) Version not compatable.

### ISSUE THREAD

**Issue by Saelman** [AnvilPowered/Catalyst#28]
Hi im running a multi velocity server. currently all the servers are running on the same build of spigot for 1.16.2

When running the /server command, im met with "the server you are attempting to connect to is running a different Minecraft version!" all the servers should be on the EXACT same build. We dont run ViaVersion and have tried turning the version check off via the config but we still get this error.

**Comment by LGCMcLovin** [comment]
I will setup a barebones network using spigot for 1.16.2 later today and test this issue

**Comment by STG-Allen** [comment]
Please try using v0.2.0 and see if the issue persists.
