### ISSUE TITLE
Display online players in discord chat [Feature] 

### ISSUE THREAD

**Issue by denkk0** [AnvilPowered/Catalyst#29]
Add a command for discord so you can see who is online on servers.
!online / !players

**Comment by paz** [comment]
how about allowing commands to be passed through, with a whitelist? this is what DiscordSRV does, it also allows you to add canned responses eg !website would return "**Our website:** website.com"

**Comment by STG-Allen** [comment]
I added !online, !players and !list here: d14d68510ce3c125f9a1c3beafb9ee5a81417b19
