### ISSUE TITLE
[Feature] Console Channel

### ISSUE THREAD

**Issue by drazisil** [AnvilPowered/Catalyst#33]
I would love to have a console channel option. I don't use staff chat (That's what discord is for) but being able to see and run commands without needing to login to the box is very helpful.

This is a feature of DiscordSRV.

**Comment by STG-Allen** [comment]
You can run !cmd (command) in any channel that is linked.

**Comment by drazisil** [comment]
Yes, but that doesn't get me streaming console output into the channel

**Comment by alexstaeding** [comment]
I think a dedicated discord channel for the console is a good addition.

**Comment by LGCMcLovin** [comment]
This would also cause serious rate-limiter issues with discord, and would disable the functionality if implemented.

**Comment by STG-Allen** [comment]
This is entirely out of scope as catalyst isn't a "logging" plugin. However, I can show you how to configure velocity to run in "tmux" so you can interact with it via ssh.

**Comment by drazisil** [comment]
I know how to do that. I guess I will stick with Discord SRV for now.
Please feel free to re-close.
- Joe Becher
