### ISSUE TITLE
ServerListPlus + Catalyst error

### ISSUE THREAD

**Issue by SirOMGitsYOU** [AnvilPowered/Catalyst#40]
**Describe the bug**
A clear description of the bug:
When using ServerListPlus to run the MOTD and player count message you get a large error message whenever pining the server (even if invalid hostname) 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install ServerListPlus dev build for Velocity
2. Install Catalyst and Anvil
3. Launch Velocity
4. Refresh multiplayer list in Minecraft so server is pinged
5. profit?

**Expected behavior**
Not to have the giant error message.

**Screenshots**
see log below

**Desktop (please complete the following information):**
 - Velocity Version: Velocity 1.1.0-SNAPSHOT (git-5d287306-b243)
 - Catalyst Version: 0.2.1
 - Additional Plugins installed on velocity: LuckPerms, Maintenance, ServerListPlus.

**Additional context**
https://pastebin.com/raw/X4DLdpGE

**Comment by paz** [comment]
Not sure if this issue is still present, but as a workaround/alternative you could use MiniMOTD. I prefer this plugin instead of ServerListPlus and it works perfectly with Catalyst.

**Comment by STG-Allen** [comment]
This has been fixed by the toggle config option.
