### ISSUE TITLE
[Feature] Weight ordered ranks in the Tablist

### ISSUE THREAD

**Issue by SirOMGitsYOU** [AnvilPowered/Catalyst#41]
**A clear description of the feature you'd like to see implemented**
Using LuckPerms weight system have the Tablist automatically order it highest to lowest.

Example:
Owner - weight 10
Admin weight 9
Mod weight 8
VIP Weight 5
Default weight 0

Would display in that order say there is 6 players online

Bob - Admin
Dave - Owner
Sam - Mod
Jade - VIP 
Cableguy20 - default

These would then display on the tablist like so

- (Owner) Dave
- (Admin) Bob
- (Mod) Sam
- (VIP) Jade
- (Member) Cableguy20.

**Comment by STG-Allen** [comment]
Currently the tablist is displayed alphabetically, however, I do want to do an entire overhaul on the tablist to make it highly customizable. I will be making a 0.3.0 milestone for this to be added.

**Comment by STG-Allen** [comment]
This feature has been written and will be released with 0.3.0.

The order will follow the order specified in the config, if there is a group not specified in the config then that group will be automaticallyput at the bottom of the list.
