### ISSUE TITLE
Disable @everyone and @here triggers in discord.

### ISSUE THREAD

**Issue by SirOMGitsYOU** [AnvilPowered/Catalyst#43]
**Describe the bug**
A clear description of the bug:
When a user types @everyone or @here in Minecraft chat once this is streamed into discord it actually permits sending of the notification to ping all users. 

**To Reproduce**
1. Setup catalyst with discord integration
2. type @everyone or @here
3. profit?

**Expected behavior**
Not to recognise the command or not act on it or post it with it being quoted out.

**Screenshots**
![image](https://user-images.githubusercontent.com/20475516/92148765-ec556f00-ee14-11ea-9d07-34ac49566418.png)

**Desktop (please complete the following information):**
 - Velocity Version: Velocity 1.1.0-SNAPSHOT.
 - Catalyst Version: 0.2.1
 - Additional Plugins installed on velocity: n/a

**Comment by STG-Allen** [comment]
This is not an issue but rather a misunderstanding. Those who have * perms or the language admin permission will be able to use the @ here and @ everyone in game.
