### ISSUE TITLE
Disable Proxy Connection/Quit messages

### ISSUE THREAD

**Issue by Curtis3321** [AnvilPowered/Catalyst#59]
Hey,

Could you please allow an option to disable this completely? Or allow "" to simply not send anything?

I had both connection & disconnect set to "" and it does just that, sends an empty line when somebody joins/leaves. 

* Bug/Feature.

**Comment by STG-Allen** [comment]
This will be resolved when 0.4 is released. 
see: https://github.com/AnvilPowered/Catalyst/commit/1e3a22d41e690b05e51605be066e5df287114feb
