### ISSUE TITLE
Error with Discord module

### ISSUE THREAD

**Issue by greysilly7** [AnvilPowered/Catalyst#67]
**Describe the bug**
A clear description of the bug: No idea

**To Reproduce**
Steps to reproduce the behavior: Just sorta happened

**Expected behavior**
No bug to spam my console and not make my eyes hurt

**Screenshots**

**Desktop (please complete the following information):**
 - Velocity Version: Velocity 1.1.8
 - Catalyst Version: 0.3.2
 - Additional Plugins installed on velocity: anvil, luckperms, skinsrestorer, tcpshield, vbans

**Additional context**
https://hastebin.com/isanivohuf.properties
is the link to the error

**Comment by STG-Allen** [comment]
That is because of the rate limiter from Discord themselves. See the configuration for the proper fix hint: `updateInterval`

**Comment by greysilly7** [comment]
Ah ok thanks
