### ISSUE TITLE
TAB does not work at all: Velocity 3.0

### ISSUE THREAD

**Issue by kubo6472** [anvilpowered/catalyst#69]
**Describe the bug**
TAB does not work

**To Reproduce**
Use latest stable release of velocity

**Expected behavior**
TAB works like b4

**Screenshots**
After:
![image](https://user-images.githubusercontent.com/26146502/125455164-82adf37a-2025-4912-8577-40d0c3d85847.png)

**Desktop (please complete the following information):**
 - Velocity Version: 3.0
 - Catalyst Version: 0.3
 - Additional Plugins installed on velocity: LuckPerms, Nuvotifier, VotingPlugin, Snap, Plan and my private plugin that just adds +1 to slots

**Comment by STG-Allen** [comment]
Catalyst has yet to be updated for Velocity 3.0.0.

**Comment by kubo6472** [comment]
> Catalyst has yet to be updated for Velocity 3.0.0.

Does that require Anvil update as well? Because some of its features work. At least I think they do.
