### ISSUE TITLE
[Feature] Send all users

### ISSUE THREAD

**Issue by ChipWolf** [AnvilPowered/Catalyst#70]
**A clear description of the feature you'd like to see implemented**

Support `@a` operator in /send command

**Comment by benfoster04** [comment]
Hey, just trawled through the common and found this in the send command:

https://github.com/AnvilPowered/Catalyst/blob/088793a6de30fe200169ef365a1a8a319c127492/catalyst-common/src/main/java/org/anvilpowered/catalyst/common/command/SendCommand.java#L73
```java
        if (target.equals("_a")) {
            CompletableFuture.runAsync(() -> {
                int total = 0;
                for (TPlayer p : userService.getOnlinePlayers()) {
                    if (locationService.getServerForName(serverName).map(s -> s.connect(p).join()).orElse(false)) {
                        ++total;
                        textService.builder()
                            .append(pluginInfo.getPrefix())
                            .green().append("You have been sent to ")
                            .gold().append(serverName)
                            .green().append(" by ")
                            .gold().append(userName)
                            .sendTo(p);
                    }
                }
                textService.builder()
                    .append(pluginInfo.getPrefix())
                    .green().append("You have sent ")
                    .gold().append(total)
                    .green().append(" players to ")
                    .gold().append(serverName)
                    .sendTo(context.getSource());
            });
            return 1;
        }
```

As seen, there is a way to do it. You'll see by that argument check and below that it iterates over each online user and attempts a connection to the specified server name. I'll do some extra digging on exactly how but it certainly looks like it's possible.

**Comment by benfoster04** [comment]
It'll help if you could give some further context on the environment you're running? (Velocity, Bungee etc)

**Comment by ChipWolf** [comment]
Velocity

**Comment by benfoster04** [comment]
Just did this with a friend of mine in production: `/send _a <server>` worked perfectly. There's probably a more user-friendly setting somewhere that I don't know about but that syntax does work.
